<a href="https://colab.research.google.com/github/akashjeez/Notebooks/blob/main/Python_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 **Python Numpy**
- NumPy -> Numerical Python (Numerical Analysis Computing Package).
- Core Library for Scientific Computing in Python.
- Provides High Performance Multi-Dimensional Array Object and Tools for Working with these Arrays.
- Advantages of Numpy over List are Less Memory, Fast and Convenient.
- Mathematical and Logical Operations on Arrays can be Performed.
- Functions for Working in Domain of Linear Algebra, Fourier Transform, and Matrices.
- Numpy Operations: Find Dimension of Array, Find Byte Size of Each Element, Find Data Type of the Elements, Find Size and Shape of an Array, Reshaping, Slicing.
- General DataType of Numpy is int8,16,32,64 etc, float64, U means Unicode String, S means String etc.


**Reference**

- <a href = 'https://numpy.org/doc/stable/' target = '_blank'> NumPy </a> 
| <a href = 'https://w3schools.com/python/numpy/numpy_intro.asp' target = '_blank'> W3Schools </a>
| <a href = 'https://tutorialspoint.com/numpy/index.htm' target = '_blank'> Tutorials Point </a>
| <a href = 'https://realpython.com/numpy-tutorial/' target = '_blank'> Real Python </a>
| <a href = 'https://datacamp.com/community/tutorials/python-numpy-tutorial' target = '_blank'> Data Camp </a>
| <a href = 'https://javatpoint.com/numpy-tutorial' target = '_blank'> JavaTPoint </a>
| <a href = 'https://edureka.co/blog/python-numpy-tutorial/' target = '_blank'> Edureka </a>
| <a href= 'https://learnpython.org/en/Numpy_Arrays' target = '_blank'> Learn Python </a>
| <a href= 'https://geeksforgeeks.org/python-numpy/' target = '_blank'> Geeks For Geeks </a>
| <a href= 'https://guru99.com/numpy-tutorial.html' target = '_blank'> Guru99 </a>

In [11]:
!pip install numpy --upgrade

Requirement already up-to-date: numpy in /usr/local/lib/python3.7/dist-packages (1.21.0)


In [2]:
import os, sys, time
import numpy as np

In [3]:
## Set Seed for Reproducibility to Receive the Exact Same Results Every Time.
np.random.seed(seed = 1234)

In [4]:
## Scalar | 0 D Tensor | A Single Value.
x = np.array(6)
print(f'x = { x }')
print(f'x ndim = { x.ndim }') # Get Number of Dimensions
print(f'x shape = { x.shape }') # Get Dimensions
print(f'x size = { x.size } ') # Get Size of Elements
print(f'x dtype = { x.dtype } ') # Get DataType

x = 6
x ndim = 0
x shape = ()
x size = 1 
x dtype = int64 


In [5]:
## Vector | 1 D Tensor | Row or Column of Values.
x = np.array( [1.3 , 2.2 , 1.7] )
print(f'x = { x }')
print(f'x ndim = { x.ndim }') # Get Number of Dimensions
print(f'x shape = { x.shape }') # Get Dimensions
print(f'x size = { x.size } ') # Get Size of Elements
print(f'x dtype = { x.dtype } ') # Get DataType

x = [1.3 2.2 1.7]
x ndim = 1
x shape = (3,)
x size = 3 
x dtype = float64 


In [6]:
## Matrix | 2 D Tensor | Arrays (Row and Column) of Values.
x = np.array( [ [1, 2], [3, 4] ] )
print(f'x = \n{ x }')
print(f'x ndim = { x.ndim }') # Get Number of Dimensions
print(f'x shape = { x.shape }') # Get Dimensions
print(f'x size = { x.size } ') # Get Size of Elements
print(f'x dtype = { x.dtype } ') # Get DataType

x = 
[[1 2]
 [3 4]]
x ndim = 2
x shape = (2, 2)
x size = 4 
x dtype = int64 


In [10]:
## 3 D Tensor | Array of Arrays (Row and Column) of Values.
x = np.array( [ [ [1, 2], [3, 4] ], [ [5, 6], [7, 8] ] ] )
print(f'x = \n{ x }')
print(f'x ndim = { x.ndim }') # Get Number of Dimensions
print(f'x shape = { x.shape }') # Get Dimensions
print(f'x size = { x.size } ') # Get Size of Elements
print(f'x dtype = { x.dtype } ') # Get DataType

x = 
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
x ndim = 3
x shape = (2, 2, 2)
x size = 8 
x dtype = int64 


In [ ]:
np.zeros